name: 'Delete old artifacts'

on:
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: Caproni/BennettFamilySiteUi
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days
