name: 'Delete old artifacts'

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolvap/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days
